---
title: "Lab 4B"
author: "Jessica Atuahene"
date: "9/29/2020"
output: html_document
Bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data/surveys_complete.csv")
```

```{r}
surveys_complete <- read_csv("data/surveys_complete.csv")
``` 
```{r, building_ggplot}
## To build a ggplot, we will use the following basic template that can be used for different types of plots:

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()
```

```{r, trendline}
### To add a geom to the plot use + operator. Because we have two continuous variables, let’s use geom_point() first:

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()
```

### Challenges 
```{r, challenge}
## To use hexagonal binning with ggplot2, first install the R package hexbin from CRAN:

install.packages("hexbin")
library("hexbin")
```

```{r, challenges}
surveys_plot <- ggplot(data = surveys_complete, 
                       mapping = aes(x = weight, y = hindfoot_length))
``` 

```{r}
## Then use the geom_hex() function:

surveys_plot +
 geom_hex()
```


```{r, building_plot}
## Building plots with ggplot2 is typically an iterative process. We start by defining the dataset we’ll use, lay out the axes, and choose a geom:

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point()
```

```{r, modify_plot}
## Then, we start modifying this plot to extract more information from it. For instance, we can add transparency (alpha) to avoid overplotting:

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1)
```

```{r, adding_color}
## We can also add colors for all the points:
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, color = "orange")
```

```{r,  }
##  where we color with species_id:
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, aes(color = species_id))
``` 
### Challenge 1 
```{r, Challenge1}
## Use what you just learned to create a scatter plot of weight over species_id with the plot types showing in different colors. Is this a good way to show this type of data?

ggplot(data = surveys_complete, 
       mapping = aes(x = species_id, y = weight)) +
   geom_point(aes(color = plot_type))
```

### Boxplots 
```{r, visualize_distrubituion}
## We can use boxplots to visualize the distribution of weight within each species:

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot()
```

```{r, adding_points}
##By adding points to the boxplot, we can have a better idea of the number of measurements and of their distribution:

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot(alpha = 0) +
    geom_jitter(alpha = 0.3, color = "tomato")
```

```{r}
## Replace the box plot with a violin plot; see geom_violin().

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_violin()
```

```{r}
## Represent weight on the log10 scale; see scale_y_log10()

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_violin() +
  scale_y_log10()
```

```{r}
## Try making a new plot to explore the distribution of another variable within each species.

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
    geom_boxplot() +
    geom_jitter(aes(color = "plot_id"))
```

Plottting time series
```{r} 
## Let’s calculate number of counts per year for each genus. First we need to group the data and count records within each group:

yearly_counts <- surveys_complete %>%
  count(year, genus)
```
 
```{r}
## Timelapse data can be visualized as a line plot with years on the x-axis and counts on the y-axis:

ggplot(data = yearly_counts, aes(x = year, y = n)) + geom_line()
```
 
```{r}
##  We need to tell ggplot to draw a line for each genus by modifying the aesthetic function to include group = genus:

ggplot(data = yearly_counts, aes(x = year, y = n, group = genus)) +
    geom_line()
```

```{r}
## We will be able to distinguish species in the plot if we add colors (using color also automatically groups the data):

ggplot(data = yearly_counts, aes(x = year, y = n, color = genus)) +
    geom_line()
```

```{r}
## In the previous lesson, we saw how to use the pipe operator %>% to use different functions in a sequence and create a coherent workflow. We can also use the pipe operator to pass the data argument to the ggplot() function. The hard part is to remember that to build your ggplot, you need to use + and not %>%.

yearly_counts %>% 
    ggplot(mapping = aes(x = year, y = n, color = genus)) +
    geom_line()
```

```{r}
## The pipe operator can also be used to link data manipulation with consequent data visualization.

yearly_counts_graph <- surveys_complete %>%
    count(year, genus) %>% 
    ggplot(mapping = aes(x = year, y = n, color = genus)) +
    geom_line()

yearly_counts_graph
```

###Faceting
```{r}
## ggplot has a special technique called faceting that allows the user to split one plot into multiple plots based on a factor included in the dataset. We will use it to make a time series plot for each species:

ggplot(data = yearly_counts, aes(x = year, y = n)) +
    geom_line() +
    facet_wrap(facets = vars(genus))
```

```{r}
## Now we would like to split the line in each plot by the sex of each individual measured. To do that we need to make counts in the data frame grouped by year, genus, and sex:

 yearly_sex_counts <- surveys_complete %>%
                      count(year, genus, sex)
```

```{r}
## We can now make the faceted plot by splitting further by sex using color (within a single plot):
ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(facets =  vars(genus))
```

```{r}
## You can also organise the panels only by rows (or only by columns):
# One column, facet by rows

ggplot(data = yearly_sex_counts, 
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(rows = vars(genus))

# One row, facet by column
ggplot(data = yearly_sex_counts, 
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(cols = vars(genus))
```
##ggplot_themes 
```{r}
## we can change our previous graph to have a simpler white background using the theme_bw() function:

 ggplot(data = yearly_sex_counts, 
        mapping = aes(x = year, y = n, color = sex)) +
     geom_line() +
     facet_wrap(vars(genus)) +
     theme_bw()

ggplot(data = yearly_sex_counts, 
        mapping = aes(x = year, y = n, color = sex)) +
     geom_line() +
     facet_wrap(vars(genus)) +
     theme_dark()

```
 ###Challenge1 
```{r}
##Use what you just learned to create a plot that depicts how the average weight of each species changes through the years.

yearly_weight <- surveys_complete %>%
                group_by(year, species_id) %>%
                 summarize(avg_weight = mean(weight))
#> `summarise()` regrouping output by 'year' (override with `.groups` argument)
ggplot(data = yearly_weight, mapping = aes(x=year, y=avg_weight)) +
   geom_line() +
   facet_wrap(vars(species_id)) +
   theme_void()

```
```{r, customization}
## Now, let’s change names of axes to something more informative than ‘year’ and ‘n’ and add a title to the figure:

ggplot(data = yearly_sex_counts, aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
         x = "Year of observation",
         y = "Number of individuals") +
    theme_dark()

```
  
```{r}
## The axes have more informative names, but their readability can be improved by increasing the font size. This can be done with the generic theme() function:
ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_bw() +
    theme(text=element_text(size = 16))
```

```{r}
## We can also modify the facet label text (strip.text) to italicize the genus names:

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_bw() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                        axis.text.y = element_text(colour = "grey20", size = 12),
                        strip.text = element_text(face = "italic"),
                        text = element_text(size = 16))
```

```{r}
## If you like the changes you created better than the default theme, you can save them as an object to be able to easily apply them to other plots you may create:

grey_theme <- theme(axis.text.x = element_text(colour="grey20", size = 12, 
                                               angle = 90, hjust = 0.5, 
                                               vjust = 0.5),
                    axis.text.y = element_text(colour = "grey20", size = 12),
                    text=element_text(size = 16))

ggplot(surveys_complete, aes(x = species_id, y = hindfoot_length)) +
    geom_boxplot() +
    grey_theme
```

```{r}
## Use the RStudio ggplot2 cheat sheet for inspiration.

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_dark() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                        axis.text.y = element_text(colour = "grey20", size = 7),
                        strip.text = element_text(face = "italic"),
                        text = element_text(size = 11))
```

Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].
### References 
```
@Misc{Chang2015,
  Title                    = {shiny: Web Application Framework for R. R package version 0.12.1},
  Author                   = {Chang, W. and Cheng, J. and Allaire, JJ. and Xie, Y. and McPherson, J. },
  Year                     = {2015},
  Type                     = {Computer Program},
  Url                      = {http://CRAN.R-project.org/package=shiny}
}
@Article{RCoreTeam,
  Title                    = {R: A Language and Environment for Statistical Computing},
  Author                   = {{R Core Team}},
  Year                     = {2015},
  Type                     = {Journal Article},
  Url                      = {http://www.R-project.org}
}
```




