---
title: "Lab6.Rmd"
author: "Jessica Atuahene"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(plotly)
library(RColorBrewer)
library(ggplot2)
```

### Exercise1 
```{r, exercise1}

daily_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") 
    
ggplot(daily_report, aes(x = Long, y = Lat, size = Confirmed/1000)) +
    borders("world", colour = NA, fill = "grey90") +
    theme_bw() +
    geom_point(shape = 21, color='yellow', fill='blue', alpha = 0.5) +
    labs(title = 'World COVID-19 Confirmed cases',x = '', y = '',
        size="Cases (x1000000))") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5)
```

### Exercise 2
```{r, exercise2}
##Update Anisa Dhana’s graph layout of the US to 9/26/2020. You may need to adjust the range or change to a linear scale (delete trans=“log”)
daily_report_ex2 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Country_Region == "US") %>% 
  filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa",
                  "Puerto Rico","Northern Mariana Islands", 
                  "Virgin Islands", "Recovered", "Guam", "Grand Princess",
                  "District of Columbia", "Diamond Princess")) %>% 
  filter(Lat > 0)

### change range= c(1,3) to visualize better
mybreaks <- c(100, 1000, 10000, 100000, 1000000)
ggplot(daily_report_ex2, aes(x = Long, y = Lat, size = Confirmed)) +
    borders("state", colour = "white", fill = "grey90") +
    geom_point(aes(x=Long, y=Lat, size=Confirmed, color=Confirmed),stroke=F, alpha=0.7) +
  
    scale_size_continuous(name="Cases", trans="log", range=c(1,3), 
                        breaks=mybreaks, labels = c("100-999",
                        "1,000-9,999", "10,000-99,999", "100,000-999,999", "1,000,000-9,999,999")) +
  
    scale_color_viridis_c(option="viridis",name="Cases",
                        trans="log", breaks=mybreaks, labels = c("100-999",
                        "1,000-9,999", "10,000-99,999", "100,000-999,999", "1,000,000-9,999,999"))  +

  ## cleaning up the graph 
    theme_void() + 
    guides( colour = guide_legend()) +
    labs(title = "Anisa Dhana's lagout for COVID-19 Confirmed Cases in the US'") +
    theme(
      legend.position = "bottom",
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#ffffff", color = NA), 
      panel.background = element_rect(fill = "#ffffff", color = NA), 
      legend.background = element_rect(fill = "#ffffff", color = NA)
    ) +
    coord_fixed(ratio=1.5)

```


### Exercise 3

```{r, exercise 3}
## Update the above graph “Number of Confirmed Cases by US County” to 9/26/2020 and use a different color scheme or theme

report_09_26_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
rename(Long = "Long_") %>% 
unite(Key, Admin2, Province_State, sep = ".") %>% 
group_by(Key) %>% 
summarize(Confirmed = sum(Confirmed)) %>% 
mutate(Key = tolower(Key))
# dim(report_09_26_2020)
# get and format the map data
us_ex3 <- map_data("state")
counties_ex3 <- map_data("county") %>% 
  unite(Key, subregion, region, sep = ".", remove = FALSE)
# Join the 2 tibbles
state_join_ex3 <- left_join(counties_ex3, report_09_26_2020, by = c("Key"))
# sum(is.na(state_join$Confirmed))

# plot new data
ggplot(data = us_ex3, mapping = aes(x = long, y = lat, group = group)) + coord_fixed(1.3) + 
  # Add data layer
  borders("state", colour = "Black") +
  geom_polygon(data = state_join_ex3, aes(fill = Confirmed)) +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "Set2"),
                       breaks = c(1, 10, 100, 1000, 10000, 100000),
                       trans = "log10", na.value = "White") +
  ggtitle("Number of Confirmed Cases by US County") +
  theme_bw() 
```

#Exercise 4
```{r,exercise4}
#Make an interactive plot using a state of your chosing using a theme different from used in the above exammples.
#Change Massachusetts to Hawaii
daily_report_4 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State == "New York") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))
```
```{r}
library(plotly)
```

```{r}
US4 <- map_data("state")
ny_us <- subset(US4, region == "new york")
counties <- map_data("county")
ny_county <- subset(counties, region == "new york")
state_join_ex4 <- left_join(ny_county, daily_report_4, by = c("subregion" = "Admin2")) 

# plot state map

ggplotly(
  ggplot(data = ny_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
# Add data layer
  geom_polygon(data = state_join_ex4, aes(fill = Confirmed), color = "blue") +
  ggtitle("COVID-19 Cases in NY (9/26/20)") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.title = element_blank()) +
  scale_fill_viridis(option="plasma")
)
```

# Exercise 5

```{r}
#Create a report with static maps and interactive graphs that is meant to be read by others (e.g. your friends and family). Hide warnings, messages and even the code you used so that it is readable. Included references. Link to the Lab 6 report from your Github site. Submit the link to Moodle.
```

* Lab 6x:[Covid-19 Reports](Lab6)

# REFERENCES 

Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015]. Data aquired from [@JohnsHopkinsUniversity].

